"use strict";

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const jsonPath = path.join(root, "content", "eras.json");
const dataJsPath = path.join(root, "src", "data", "data.js");

// --- Normalization (inlined) ---

function artworksToObjects(era) {
  return era.artworks.slice(0, 3).map((a) => ({
    title: a.title,
    artist: a.artist,
    date: a.date,
    medium: a.keyFeatures[0] ?? "—",
    context: `${a.title} (${era.title})`,
    story: a.workBlurb,
  }));
}

function normalizeEra(era) {
  const compareTags = [era.filterFacet, era.visualMood];
  const objects = artworksToObjects(era);
  return { ...era, compareTags, objects };
}

function normalizeEras(eras) {
  return eras.map(normalizeEra);
}

// --- Build ---

const { eras } = JSON.parse(fs.readFileSync(jsonPath, "utf8"));

const museumData = normalizeEras(eras);
const body = `/* Generated by npm run build:data from content/eras.json */\nconst museumData = ${JSON.stringify(museumData, null, 2)};\n`;

fs.writeFileSync(dataJsPath, body, "utf8");
console.log("Wrote", dataJsPath);
