"use strict";

const fs = require("fs");
const path = require("path");
const { normalizeEras } = require("./normalize-era.cjs");
const { eras } = require("./eras-data.cjs");

const root = path.join(__dirname, "..");
const jsonPath = path.join(root, "content", "eras.json");
const dataJsPath = path.join(root, "src", "data", "data.js");

fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
fs.writeFileSync(jsonPath, JSON.stringify({ eras }, null, 2), "utf8");
console.log("Wrote", jsonPath);

const museumData = normalizeEras(eras);
const body = `/* Generated by npm run build:data from scripts/eras-data.cjs */
const museumData = ${JSON.stringify(museumData, null, 2)};
`;
fs.writeFileSync(dataJsPath, body, "utf8");
console.log("Wrote", dataJsPath);
